image: docker/compose:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - docker build -t backend .

test:
  stage: test
  before_script:
    - cd BuildTesting
    - docker-compose up &
    - cd ..
  script:
    - mvn spring-boot:run &
    - ./wait-for-spring.sh
    - mvn test

deploy:
  stage: deploy
  script:
    - docker login -u brandonfox -p $gitlab-password registry.gitlab.com
    - docker build -t registry.gitlab.com/brandonfox/backend-project-2-backend .
    - docker push registry.gitlab.com/brandonfox/backend-project-2-backend
