version: "3.7"

services:
  db:
    container_name: "Testsql"
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "backend4backend"
      MYSQL_USER: "server"
      MYSQL_PASS: "serverPass"
      MYSQL_DATABASE: "backenddb"
    ports:
    - 3306:3306